### ISSUE TITLE
allow RESTful API accesses (with tokens in QS or POST

### ISSUE THREAD

**Issue by natnat-mc** [natnat-mc/kfet#15]

**Comment by pierre42100** [comment]
And the login tokens must absolutely be linked with the API client that made the authentication !

In fact, you should consider your webui as a client of your API (like I did with Comunic). It makes things much logical and easier after...

**Comment by natnat-mc** [comment]
How did I not think of that!

Do I link them by IP, by User-Agent string?

(I already consider my webui as a client, just with cookies as a bonus to store the session somewhere; everything will do REST calls and WebSocket accesses)

**Comment by natnat-mc** [comment]
Make cookies actually carry tokens, like in #16
Sign tokens with a server secret, and store everything inside them, not a db

**Comment by pierre42100** [comment]
Yes cookies should carry tokens so you would have to check both API and User tokens before confirming user authentication...

**Comment by natnat-mc** [comment]
as of 9a07ef51d15ac076cfc161a9d603700f752f6917, tokens can be in
- query string `GET url?token=<token>`
- header `Token: <token>`
- cookies `session=<token>`

**Comment by natnat-mc** [comment]
tokens should be JWT's (#21)

**Comment by natnat-mc** [comment]
this should have been closed sooner
